services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: bijyou_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bijyou_pgdata:/var/lib/postgresql/data

volumes:
  bijyou_pgdata:
